= Companion Devices Working Group (CD-WG)

image::https://img.shields.io/badge/Contributor%20Covenant-v2.0%20adopted-ff69b4.svg[link="code_of_conduct.adoc]

== Introduction
This is the primary repository for the Companion Devices Working Group. 

This is the primary repository for the Companion Devices Working Group and its work on creating collaborative Protection Profiles and related supporting documents. The Common Criteria Portal page can be found https://www.commoncriteriaportal.org/communities/dedicated_security_components.cfm[here].

== The Technical Community
The CD-WG consists of members of Certification Bodies, labs, vendors and academia working together to create requirements for the testing of Companion Devices. A Companion Device is a device which extends the functionality of a primary/base device. This could be anything from a smart watch to a medical device where they are paired to another device, such as a smartphone or laptop.

If you are interested to join the WG and become a member of the mailing list, please send an email with a short request to compdev-wg@freelists.org.

== Code of Conduct
The CD-WG expects participants to follow a code of conduct. This is laid out in the https://github.com/CompDev-WG/Governance[Terms of Reference] and in the https://github.com/CompDev-WG/Governance/code_of_conduct.adoc[Code of Conduct].

== Contributing to the CD-WG
The CD-WG welcomes contributions to the ongoing work of creating and maintaining the cPP and SD. Issues and Pull Requests can be submitted at any time for review by the iTC. New Issues can be submitted https://github.com/CompDev-WGcPP/issues/new/choose[here].

The CD-WG uses asciidoc files as the source files for generating the cPP and all related documents. Asciidoc is a text format that can be read directly in GitHub as well as offline using any number of editors (including simple text editors). https://asciidoctor.org[Asciidoctor] is used as the post-processor for generating the final (i.e. PDF or HTML) output from these files. The format of these files is fairly simple to understand.

A syntax guide for the main flags you are likely to run into can be found in the the iTC Team Tools WG repository https://github.com/itc-wgtools/cPP-Tools/tree/master/User%20Guidance[Syntax Guide]. This file is designed to be viewed as both source and output (to see what the flags do). Questions about the syntax can be posted to as an https://github.com/itc-wgtools/cPP-Tools/tree/master/User%20Guidance[Issue] to that WG.

=== CD-WG Workflow
The CD-WG generally utilizes a GitHub workflow for accepting new changes into the documents. An outline of this workflow can be found at the https://itc-wgtools.github.io/admin-guide/Maint-Project-Flow.html[iTC Documentation Workflow] page provided by the iTC Team Tools WG.

== Branches
The CD-WG has three primary branches:

[cols=".^1,.^3",options="header"]
|===
|Branch
|Description

|Master
|The current, approved released version of the documents.

|Working
|The active branch for next version of the documents.

|Interpretation
|This branch is for working on technical decisions to the current, published release. (Not enabled yet)

|===

All Pull Requests should be made to the https://github.com/CompDev-WG/cPP/tree/working[Working] branch.

== Files Description
This table provides an overview of the files in the repository.

[cols=".^1,.^1,.^3",options="header"]
|===

|Folder
|File
|Description

|Protection Profile
|CD-PPM.adoc
|The Companion Devices PP-Module

|Supporting Documents
|CD-SD.adoc
|The Supporting Documentation for the PP-Module

|PP-Configurations
|PP-config.adoc
|Initial template for PP-Configuration

|Security Problem Definition
|CD-SPD.adoc
|The SPD for the Companion Devices

|===
